### PR TITLE
implement new front end for the demo

### PR DESCRIPTION
**Pull request by olivinesguerra**
I used expo on the new repo.

### CODE REVIEW

**Comment by kpachhai** [comment]
Hmm. From what I know about expo, it's great but does it play well when we're dealing with so many custom native modules and bridges? Thoughts, @ademcan and @liyangwood ?

**Comment by olivinesguerra** [comment]
Hi Sir. I just use expo for importing npm packages. They are the one handling the import.

**Comment by olivinesguerra** [comment]
@ademcan based from the task. I think the views are all revamp.

**Comment by olivinesguerra** [comment]
BTW. @ademcan i create a sample NPM package. it works on the expo app.. And still this is just a demo.

**Comment by olivinesguerra** [comment]
I think there are complication on using EXPO. beside expo is the one that make me love React Native. Because of this manual importing that causes me to quit using it from start. Aside from that, our library is more on functionality :D no UI. So I think there will be no problem on using it. And if the library does not work on expo? I think there is a problem on the library itself. Because right now I'm using expo on 3 projects I have'nt experience anything bad beside when the library itself has a problem on react-native version...

**Comment by olivinesguerra** [comment]
And again its just a demo 👍

**Comment by EricDualc** [comment]
This was done already without using expo.
So I think, we need to close this PR.

**Pull request closed without merging**
