### PR TITLE
Create wallet using the cpp library (iOS)

### PR DESCRIPTION
**Pull request by ademcan**

### CODE REVIEW

**Comment by andersalm** [comment]
@EricDualc can you review this when the conflict has been resolved?

**Comment by kpachhai** [comment]
@ademcan Looks like there are some conflicts. Can we resolve them before they're merged?

**Comment by EricDualc** [comment]
@ademcan Would you please fix this tiny conflict so that I can approve your PR?

**Comment by sarawut11** [comment]
@ademcan Have you changed my frontend code or just only added your code for ios?

**Pull request merged**
