### PR TITLE
change library from c to cpp

### PR DESCRIPTION
**Pull request by EricDualc**

### CODE REVIEW

**Comment by ademcan** [comment]
Thanks @EricDualc, did you try the new demo app on simulator or real device?

**Comment by EricDualc** [comment]
yes, I tried it on real device, I'll share the video on the channel soon.

**Comment by EricDualc** [comment]
It's alright to accept the PR, I tested on my side.

**Comment by ademcan** [comment]
If I understand correctly, you are here loading the cpp lib to the RN app, not using the react-native-elastos-wallet-core repo/package, is that right?

**Comment by ademcan** [comment]
Ok, got it now!

**Pull request merged**
